### ISSUE TITLE
Release cycle/notes

### ISSUE THREAD

**Issue by jody-zeitler** [dcmjs-org/dcmjs#100]
I've been waiting on a few bug fixes to make their way into an NPM release. Since 0.10.0 there has been a 0.10.1 NPM version with no accompanying Git tag, and then a 0.11.0 version with no apparent changes to source https://github.com/dcmjs-org/dcmjs/compare/v0.10.0...v0.11.0. It would be excellent if there were signed releases in Github that correspond to packages that are published to NPM, with a summary of all the PRs included.

Alternatively, since this is a volatile project, would it be possible to include the `src` directory within the published NPM package so that we would be to install directly from a Git repo without having to update our import strings?

**Comment by dannyrb** [comment]
:wave: Hi @jody-zeitler!

This repository has automatic release/versioning (and tagging) via CircleCI + Semantic Release. For that to trigger/work, commits (or merge commits) need to use the correct syntax, see:

https://semantic-release.gitbook.io/semantic-release/#commit-message-format

Unfortunately, it looks like on the last few merges, we did not update the merge commit to use the correct syntax for the changes that took place. I wouldn't be surprised if we also accidentally did a manual release instead of using this system.

I'll revert and reapply some of the recent PRs. Hopefully this addresses this issue. Outside of that, I'm not sure there's much we can do except educate maintainers.

**Comment by pieper** [comment]
Hi @dannyrb could you update the readme with specific instructions?  (I must not have been paying attention, because I totally didn't know about or forgot this auto-release thing was set up!)

I have been doing these steps when it I want to update the package:
 
https://github.com/dcmjs-org/dcmjs#for-maintainers

**Comment by dannyrb** [comment]
Going to re-open this. Maybe I'm spending too much time over in OHIF/Cornerstone land :sweat_smile: 

It looks like, despite having CI in place, it's not quite doing the trick. I'll consider this an issue advocating for it to be fully implemented. See recent merge PRs:

https://app.circleci.com/jobs/github/dcmjs-org/dcmjs/95

**Comment by pieper** [comment]
@jody-zeitler thanks for bringing this up, clearly we need to sort this out and get on the same page 😄 

@dannyrb can we also turn on testing in the ci?

Would it just be adding `-run: npm test` after [this line](https://github.com/dcmjs-org/dcmjs/blob/master/.circleci/config.yml#L23)?

**Comment by dannyrb** [comment]
@pieper we can enforce passing tests before merge of a PR is allowed. That would be a separate workflow.

**Comment by dannyrb** [comment]
Tests now run on PRs: 

![image](https://user-images.githubusercontent.com/5797588/76227300-7a99c100-61f5-11ea-9a79-6cbed3df451b.png)

Semantic versioning via Commit Messages in place:

- CI Workflow: https://app.circleci.com/pipelines/github/dcmjs-org/dcmjs/268/workflows/5eee11a8-6599-4f9e-b7fa-ba98dd6e1c07/jobs/101

![image](https://user-images.githubusercontent.com/5797588/76227546-d95f3a80-61f5-11ea-9e07-64e43c279ac7.png)

**Comment by jody-zeitler** [comment]
Awesome thank you!
