### ISSUE TITLE
dcmjs.data.DicomMessage.readFile() fails for certain dicom SR

### ISSUE THREAD

**Issue by ChrisWoodlief** [dcmjs-org/dcmjs#125]
Hi, we have been using the dcmjs.data.DicomMessage.readFile function on Dicom SRs. We have found a case where other dicom parsing solutions like [Dicom Parser](https://rawgit.com/cornerstonejs/dicomParser/master/examples/dumpWithDataDictionary/index.html) and RadiAnt DICOM Viewer are able to parse the file correctly. But dcmjs is having an issue. Here is how we are using DicomMessage.readFile:

<img width="1253" alt="dcmjs stack" src="https://user-images.githubusercontent.com/5483193/83155681-7a5fe200-a0cf-11ea-8134-3ab02cd9fd04.png">

Here is the file which is causing the issues:
https://medicom-dicoms.s3.amazonaws.com/publiclyposted/dcmjs_parsing_issue_SR

**Comment by pieper** [comment]
Thanks for reporting the issue and supplying the data.  I took a quick look but don't really have time to dig in right now.  Did you try stepping through in the debugger?  If you can host a little site off of github that serves the file and tries to read it with dcmjs it would be easier to dig into.

**Comment by ChrisWoodlief** [comment]
Hi @pieper !

We have tried stepping through in a debugger but once we were really deep into the dcmjs library it became a bit harder to understand the root cause of the issue. From what we have seen it seems like the reading of the tag 0040,A073 is not terminating and the reading goes past the end of the file.

Here is an off site example we made linked up to the file posted above.
https://jsfiddle.net/ds4vrq2g/2/

**Comment by pieper** [comment]
Hmm, yes, looks like maybe it's not handling nested sequences well.  You said you have similar SR files that can be read?  Did you see any obvious differences?   Maybe you can share a similar one that does work.

I inherited this code and it's worked well with a whole lot of datasets and I would have thought that all nested sequences would be basically the same, but I guess there's something unique about this one.  I see a couple sequences with no content so maybe that's not accounted for correctly.

**Comment by jssuttles** [comment]
Hi @pieper, I work together with @ChrisWoodlief.
To be able to post this DICOM here, we needed to anonymize it. When we ran it through a DICOM Editor tool (https://www.dvtk.org/dicom/editor/), the tool added a few characters to that area. Afterwards, when we tried to read the file with dcmjs, it worked. To produce the anonymized dicom as posted, we edited the DICOM as text making sure to alter just the visible characters.

Here is the diff between the posted DICOM and the DICOM Editor tool output:
![image](https://user-images.githubusercontent.com/8527741/83268049-10a90c00-a193-11ea-8499-821c81f736a3.png)

Here is the diff in hex:
![image](https://user-images.githubusercontent.com/8527741/83268395-9036db00-a193-11ea-96f1-e369a7642e45.png)

**Comment by pieper** [comment]
Very interesting - nice detective work 👍 Looks like when you ran the editor it added in the [delimitation items](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_7.5.html) that were apparently missing in the original.  I guess the other dicom libraries are more robust at handling the original variant than dcmjs. 

With these clues is there any chance you'd want to try a PR?  I'd really want to have some additional tests to make sure fixing this doesn't impact other sequence handling since that's such a central feature.

**Comment by jssuttles** [comment]
Do you have a way to run dcmjs through a suite of test datasets?
I was hoping that someone else that was familiar with the code could fix it. The area is not commented and reading bytes is an utter pain. But I'm looking into it.
What I've gathered is that the DICOM is not valid by that doc because it opens an empty item but does not close it. Instead it just closes the enclosing Sequence item.

**Comment by pieper** [comment]
Thanks for digging in - yes, I also did some debugging and I feel your pain.  Unfortunately the original developer moved on so it hasn't been touched in quite a while.

In terms of testing, you can follow the pattern in [test_data.js](https://github.com/dcmjs-org/dcmjs/blob/master/test/test_data.js) to add a test that will run with `npm run test`, but no debugger.  Otherwise just a locally hosted version of the jsfiddle code to run your local build is probably the best option.

**Comment by jssuttles** [comment]
So, I guess FUJI sometimes creates empty length SQ items. This is counter to the delimitation items page that you posted. An SQ item should have a start and an end. These have a start, a length of zero, and no end. The way that dicomParser handles this is that the parser processes what it's reading as it goes, whereas dcmjs reads what it thinks it needs to read, and then shunts the processing of the SQ element to the end.

**Comment by pieper** [comment]
If you think they are coming up in real life then we should try to support it.  I hate to see a lot of workarounds in the code but sometimes you can't avoid it.

**Comment by jssuttles** [comment]
We work on a real application where dcmjs is reading and writing files, and this file came up and caused an issue.
Maybe I'll leave more comments.

**Comment by pieper** [comment]
If you can generate a PR with some extra comments that's great.  I did take a quick look and can see how missing end-tags would mess up the logic.  I hope there's a clean fix.

**Comment by jssuttles** [comment]
https://github.com/dcmjs-org/dcmjs/pull/126

**Comment by ChrisWoodlief** [comment]
Tested and this looks good @jssuttles ! I am closing this issue
