### ISSUE TITLE
"QIICR segmentation data" example is no longer working

### ISSUE THREAD

**Issue by fedorov** [dcmjs-org/dcmjs#32]
E.g. https://pieper.github.io/dcmjs/examples/qiicr/?seriesUID=1.2.276.0.7230010.3.1.3.8323329.30077.1440006259.837527

![image](https://user-images.githubusercontent.com/313942/50011559-70552c80-ff8a-11e8-8d3b-334b0380370c.png)

**Comment by fedorov** [comment]
Thank you, this works now!

**Comment by fedorov** [comment]
@pieper it is broken again

![image](https://user-images.githubusercontent.com/313942/58975749-b6e64f80-8793-11e9-8b5a-ec49fb66de6e.png)

**Comment by fedorov** [comment]
The issue above is for the URL provided in https://github.com/dcmjs-org/dcmjs/issues/32#issuecomment-447432789

**Comment by pieper** [comment]
Sorry, yes, I guess this got broken again when the examples repository was set up.  I just fixed it so that either of the links below will work, with the later being slightly preferred.

https://dcmjs-org.github.io/dcmjs/examples/qiicr/?seriesUID=1.2.276.0.7230010.3.1.3.8323329.30077.1440006259.837527

https://examples.dcmjs.org/qiicr/?seriesUID=1.2.276.0.7230010.3.1.3.8323329.30077.1440006259.837527
