### ISSUE TITLE
RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by MiguelSotelo2** [dcmjs-org/dcmjs#88]
The goal is to read the dicom, read patient health information, deidentify it (using the same number of characters, although that may not be necessary), and modify the dataSet tags with the new de-identified values

Following the instructions in https://github.com/dcmjs-org/dcmjs/issues/64:

```
let filename = ' /path/to/image/image.dcm'; //I've opened this in python and my overall procedure works
let arrayBuffer = fs.readFileSync(filename).buffer; 
let DicomDict = dcmjs.data.DicomMessage.readFile(arrayBuffer);
```
Leads to: 

> Invalid vr type  - using UN

> RangeError: Offset is outside the bounds of the DataView

Any help is greatly appreciated!

**Comment by pieper** [comment]
Probably the data is ill-formed somehow, or otherwise something dcmjs doesn't handle (yet?).  The corrupted VR type is an obvious issue.

If you aren't working in a browser, then pydicom is a more mature solution.  Perhaps if you pre-process using pydicom you could more easily work with it in javascript.  (e.g. see https://slicer.readthedocs.io/en/latest/user_guide/module_dicompatcher.html)

**Comment by MiguelSotelo2** [comment]
You are correct. the data was ill-formatted. Thank you!

**Comment by ledinhthi** [comment]
@MiguelSotelo2, Today i got problem same with you, could you help me to solve this, i wil be appriciated.

**Comment by xionghailong1205** [comment]
me too

**Comment by pieper** [comment]
This issue is closed since the original poster determined the data was malformed.  DICOM is a complex format and many systems generate non-standard data.  It's likely you also have bad data.  There many open source tools that you can use to inspect and possibly correct the data so it will work with dcmjs.

**Comment by xionghailong1205** [comment]
think you i know i solve this problem by deleting non-standard tag
